### ISSUE TITLE
Possibility to edit userSaveGame(s)?

### ISSUE THREAD

**Issue by gbakeman** [tony56a/crp-parser#1]
I was hoping I'd be able to edit some data in my save game, unfortunately CrpParser crashes when it attempts to open a `userSaveGame` asset type. Here's the output when I try to run the tool:

```
.\CrpParser.exe -f '.\Christmas Village.crp' -v -s ./vals.txt
Package Name:Christmas Village
Package Author:Unknown
Package Format Version:6
Package Version:0
Main Asset Name:Christmas Village
Content Begin Index:370
# of Assets:4

Asset Name:Christmas Village_Data
Asset Checksum:cba46932306f6e07b0d5d1e70b9a140c
Asset Type:data
Asset Offset Begin:0
Asset Size:10040137

Asset Name:Christmas Village_SteamPreview
Asset Checksum:43df6252402afa62140521b0d0f4c8d6
Asset Type:texture
Asset Offset Begin:10040137
Asset Size:529519

Asset Name:Christmas Village_Snapshot
Asset Checksum:3e9ffe709e41e975ac443b64472220fe
Asset Type:texture
Asset Offset Begin:10569656
Asset Size:211516

Asset Name:Christmas Village
Asset Checksum:dd0412205f667e1c8fc05860d02e1a8d
Asset Type:userSaveGame
Asset Offset Begin:10781172
Asset Size:16147


Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at ConsoleApplication1.AssetParser.parseObject(Int32 length, String format, Boolean saveFile, String saveFilePath, Boolean verbose) in C:\Users\applecobbler\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\AssetParser.cs:line 50
   at ConsoleApplication1.CrpDeserializer.parseAssets(CrpHeader header, Int32 index, Boolean saveFiles, Boolean isVerbose) in C:\Users\applecobbler\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\CrpDeserializer.cs:line 120
   at ConsoleApplication1.CrpDeserializer.parseFile(Options options) in C:\Users\applecobbler\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\CrpDeserializer.cs:line 58
   at ConsoleApplication1.Program.Main(String[] args) in C:\Users\applecobbler\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 44
```

Does it not like the path from which I'm running the tool? It's `E:\Users\Glen\Downloads\CrpParser` which I can't image would be invalid.

**Comment by Perillio** [comment]
Same problem here. "Illegal characters in path". Seems to search for C:}Users}applecobbler instead of the folder its running from (tries to open CrpDeserializer.cs on that path).
